### ISSUE TITLE
Not naive datetime (tzinfo is already set) error on messages.search

### ISSUE THREAD

**Issue by jaspalpuri-zopa** [mailosaur/mailosaur-python#15]
After upgrading to version 6.0.5 I'm now hitting an exception on the messages.search method - specifically in the case where I provide a datetime object for the `received_after` argument. 

In the console I'm seeing: 
`{ValueError}Not naive datetime (tzinfo is already set)`

Which looks to be thrown by: https://github.com/mailosaur/mailosaur-python/blob/5df04903d72a63ed1e751afbba8b56db6b43bcb6/mailosaur/operations/messages_operations.py#L172

Before, I was able to pass in the datetime object and get the results of the search successfully. Is this an intentional change to the API and if so, what's the correct way to now populate the `received_after` argument? 

See attached screenshot of PyCharm Evaluate box during a debug for further details. 
![received_after bug](https://user-images.githubusercontent.com/59732020/86375132-3ab38980-bc7d-11ea-9409-db13c020117a.png)

Thanks.

**Comment by hippyhorse** [comment]
Hi @jaspalpuri-zopa,

First, really sorry for the delay in picking this one up.

This change was indeed intentional, as we were seeing customers pass in non-UTC dates, which was causing the API call to include no timezone information, causing the datetime to be misinterpreted and give unexpected results.

It appears that this code doesn't account for when the datetime passed in DOES have a timezone set already. We will investigate this and get it sorted asap.

**Comment by hippyhorse** [comment]
This is now fixed via 0cf872fe26ae51f1a5f78d3818cbf7ea745fede6 and released as part of version 7.0.2 👍
