### ISSUE TITLE
received_after parameter break functionality (7.1.0 to 7.70)

### ISSUE THREAD

**Issue by jaspalpuri-zopa** [mailosaur/mailosaur-python#19]
I recently tried to upgrade from 7.1.0 to 7.7.0, however it appears this version has changes to how the `received_after` parameter is handled and breaks functionality. My specific use case is to search for emails received after the timestamp of the last email received. This worked in 7.1.0, but in 7.7.0, however, the same email keeps being returned rather than a newly received email or an empty list. 

I suspect it's because of the setting of microsecond to 0 [here](https://github.com/mailosaur/mailosaur-python/blob/5d4548759b4f301492851a660b8756fec51cb00e/mailosaur/operations/messages_operations.py#L178): 

```python        
if received_after is not None:
    received_after = received_after.astimezone().replace(microsecond=0).isoformat()
```
Is this intentional?

**Comment by hippyhorse** [comment]
Hey @jaspalpuri-zopa, the change was intentionally done to make it easier to manage the `received_after` option. However, all `.replace(microsecond=0)` should be doing is stripping the microsecond portion from an ISO format date - instead making it accurate to the nearest second.

Because of this it's not clear why you would be getting an issue due to this - we do have test coverage for this parameter, so if there is a scenario you have that we can reproduce we'd definitely want to fix it
